print("##############################")
print("#                            #")
print("#   Ferian Desta Ashadi      #")
print("#      2410817110003         #")
print("#                            #")
print("##############################")
